### PR TITLE
Realtime tests for realtime <-> client

### LINKED ISSUE #182: Client is not deleted from victims after disconnecting
See https://github.com/dionyziz/rupture/pull/179#discussion_r72905907

Let's provide a regression test also.

### PR DESCRIPTION
**Pull request by esarafianou**
Fix #182 #183

### CODE REVIEW

File: realtime/spec/realtimespec.js [hunk 1]
```diff
@@ -38,13 +38,16 @@ function connect() {
...
 describe('real-time service', () => {
     let server,
-        socket;
+        socket,
+        socket2;
 
     beforeEach(() => {
         server = runServer();
         socket = connect();
+        socket2 = connect();
```
Comment (dionyziz) [inline realtime/spec/realtimespec.js]: This is not needed `beforeEach`

File: realtime/spec/realtimespec.js [hunk 2]
```diff
@@ -56,6 +59,25 @@ describe('real-time service', () => {
...
 
+    it('does not duplicate clients running', function(done) {
+        socket.on('connect', () => {
+            socket.emit('client-hello', {victim_id: 5});
+            socket.on('server-hello');
+        });
+        socket2.on('connect', () => {
+            socket2.emit('client-hello', {victim_id: 5});
+            socket.on('server-nowork', done);
+        });
```
Comment (dionyziz) [inline realtime/spec/realtimespec.js]: Race condition

File: realtime/spec/realtimespec.js [hunk 3]
```diff
@@ -56,6 +59,25 @@ describe('real-time service', () => {
...
+    });
+
+    it('sets client.id null, when client disconnects', function(done) {
```
Comment (dionyziz) [inline realtime/spec/realtimespec.js]: =>

File: realtime/spec/realtimespec.js [hunk 4]
```diff
@@ -56,6 +59,25 @@ describe('real-time service', () => {
         });
     });
 
+    it('does not duplicate clients running', function(done) {
```
Comment (dionyziz) [inline realtime/spec/realtimespec.js]: =>

File: realtime/spec/realtimespec.js [hunk 5]
```diff
@@ -56,6 +59,25 @@ describe('real-time service', () => {
...
+        socket.on('connect', () => {
+            socket.emit('client-hello', {victim_id: 5});
+            socket.on('server-hello');
```
Comment (dionyziz) [inline realtime/spec/realtimespec.js]: This is a noop

File: realtime/spec/realtimespec.js [hunk 6]
```diff
@@ -56,6 +59,25 @@ describe('real-time service', () => {
...
+        socket2.on('connect', () => {
+            socket2.emit('client-hello', {victim_id: 5});
+            socket.on('server-nowork', done);
+        });
+    });
+
+    it('sets client.id null, when client disconnects', function(done) {
+        socket.on('connect', () => {
+            socket.emit('client-hello', {victim_id: 5});
+            socket.on('server-hello');
```
Comment (dionyziz) [inline realtime/spec/realtimespec.js]: noop

File: realtime/spec/realtimespec.js [hunk 7]
```diff
@@ -56,6 +59,25 @@ describe('real-time service', () => {
...
+            socket.emit('disconnect', done);
```
Comment (dionyziz) [inline realtime/spec/realtimespec.js]: You're sending the "done" function to the realtime server?...

Comment (dionyziz) [inline realtime/spec/realtimespec.js]: You must test that after a client disconnects, then reconnection will not be rejected.

**Comment by dionyziz** [comment]
rebase

File: realtime/spec/realtimespec.js [hunk 8]
```diff
@@ -56,6 +57,39 @@ describe('real-time service', () => {
         });
     });
 
+    it('does not duplicate clients running', (done) => {
+        socket.on('connect', () => {
+            socket.emit('client-hello', {victim_id: 5});
+            socket2 = connect();
```
Comment (dionyziz) [inline realtime/spec/realtimespec.js]: This still has a race condition. First, `socket` connects and fires the `connect` event. Then `socket` emits a `client-hello`, but the server has not received it yet. Then `socket2` connects. However, `socket2`'s `connect` event never fires, because the `socket` has not yet received a `server-hello` and so the event was not fired.

I suggest you move the socket2 `connect` into the `server-hello` event handler to avoid this.

Comment (esarafianou) [inline realtime/spec/realtimespec.js]: Fixed

File: realtime/spec/realtimespec.js [hunk 9]
```diff
@@ -56,6 +57,39 @@ describe('real-time service', () => {
...
 
+    it('does not duplicate clients running', (done) => {
+        socket.on('connect', () => {
+            socket.emit('client-hello', {victim_id: 5});
+        });
+        socket.on('server-hello', () => {
+            socket2 = connect();
+            socket2.on('connect', () => {
+                socket2.emit('client-hello', {victim_id: 5});
+            });
```
Comment (dionyziz) [inline realtime/spec/realtimespec.js]: Write one more test to ensure two different clients with different victim ids are both accepted by the server.

Comment (esarafianou) [inline realtime/spec/realtimespec.js]: Done

File: realtime/spec/realtimespec.js [hunk 10]
```diff
@@ -56,6 +57,55 @@ describe('real-time service', () => {
...
+            socket2.on('server-nowork', () => {
+                socket2.close();
+                done();
+            });
+        });
+    });
+
+    it('sets client.id null, when client disconnects', (done) => {
```
Comment (dionyziz) [inline realtime/spec/realtimespec.js]: This description pertains to the implementation. I would change it to something like:

it('allows a client to reconnect after it disconnects')
